export interface Painting {
  id: string;
  title: string;
  medium: string;
  size: string;
  year: string;
  image: string;
  category: "perforated-newspaper" | "monochrome" | "landscape" | "portrait" | "studio";
  collection?: string;
  featured?: boolean;
}

export const paintings: Painting[] = [
  {
    id: "supa-heroii",
    title: "Supa Heroii",
    medium: "Acrylic on perforated Newspaper",
    size: "175 × 135 cm",
    year: "2023",
    image: "/paintings/supa-heroii.jpg",
    category: "perforated-newspaper",
    collection: "KfW Stiftung, Germany",
    featured: true,
  },
  {
    id: "girl-with-comb",
    title: "Her Crown",
    medium: "Acrylic on canvas",
    size: "180 × 150 cm",
    year: "2024",
    image: "/paintings/girl-with-comb.jpg",
    category: "portrait",
    featured: true,
  },
  {
    id: "girl-yellow-top",
    title: "Mwenge mwanakasi",
    medium: "Acrylic on canvas",
    size: "179 × 122 cm",
    year: "2024",
    image: "/paintings/girl-yellow-top.jpg",
    category: "portrait",
    featured: true,
  },
  {
    id: "girl-pink-dress",
    title: "Coloured Land",
    medium: "Acrylic on canvas",
    size: "177 × 134 cm",
    year: "2025",
    image: "/paintings/girl-pink-dress.jpg",
    category: "portrait",
  },
  {
    id: "girl-with-plant",
    title: "maluba maluba",
    medium: "Acrylic on canvas",
    size: "175 × 135 cm",
    year: "2024",
    image: "/paintings/girl-with-plant.jpg",
    category: "portrait",
  },
  {
    id: "girl-pink-top",
    title: "Amensi",
    medium: "Acrylic on canvas",
    size: "178 × 134 cm",
    year: "2024",
    image: "/paintings/girl-pink-top.jpg",
    category: "portrait",
    featured: true,
  },
  {
    id: "boy-drinking",
    title: "Kasuba ii",
    medium: "Acrylic on canvas",
    size: "170 × 127 cm",
    year: "2024",
    image: "/paintings/boy-drinking.jpg",
    category: "landscape",
  },
  {
    id: "boy-drinking-2",
    title: "Tumone",
    medium: "Acrylic on canvas",
    size: "197 × 127 cm",
    year: "2024",
    image: "/paintings/boy-drinking-2.jpg",
    category: "landscape",
  },
  {
    id: "couple-landscape",
    title: "Acid Rains",
    medium: "Acrylic on canvas",
    size: "177 × 134 cm",
    year: "2025",
    image: "/paintings/couple-landscape.jpg",
    category: "landscape",
    featured: true,
  },
  {
    id: "boy-yellow-boots",
    title: "Mud Puddles",
    medium: "Acrylic on canvas",
    size: "176 × 131 cm",
    year: "2024",
    image: "/paintings/boy-yellow-boots.jpg",
    category: "portrait",
  },
  {
    id: "mother-and-child",
    title: "The Lightening Power",
    medium: "Acrylic on canvas",
    size: "177 × 134 cm",
    year: "2025",
    image: "/paintings/mother-and-child.jpg",
    category: "portrait",
    featured: true,
  },
  {
    id: "three-figures",
    title: "Crocodile cries too",
    medium: "Acrylic on canvas",
    size: "169 × 128 cm",
    year: "2024",
    image: "/paintings/three-figures.jpg",
    category: "portrait",
  },
  {
    id: "cobalt-faced",
    title: "Cobalt faced",
    medium: "Acrylic on perforated Newspaper",
    size: "170 × 130 cm",
    year: "2025",
    image: "/paintings/cobalt-faced.jpg",
    category: "perforated-newspaper",
  },
  {
    id: "monochrome-triptych-women",
    title: "Mwenge I",
    medium: "Acrylic on canvas",
    size: "Triptych",
    year: "2024",
    image: "/paintings/monochrome-triptych-women.jpg",
    category: "monochrome",
  },
  {
    id: "monochrome-triptych-men",
    title: "Mwenge II",
    medium: "Acrylic on canvas",
    size: "Triptych",
    year: "2024",
    image: "/paintings/monochrome-triptych-men.jpg",
    category: "monochrome",
  },
  {
    id: "monochrome-triptych-three",
    title: "Mwenge III",
    medium: "Acrylic on canvas",
    size: "Triptych",
    year: "2024",
    image: "/paintings/monochrome-triptych-three.jpg",
    category: "monochrome",
  },
  {
    id: "perforated-series-gallery",
    title: "Black Mountain Series I",
    medium: "Acrylic on perforated Newspaper",
    size: "Installation view",
    year: "2024",
    image: "/paintings/perforated-series-gallery.jpg",
    category: "perforated-newspaper",
  },
  {
    id: "perforated-series-gallery-2",
    title: "Black Mountain Series II",
    medium: "Acrylic on perforated Newspaper",
    size: "Installation view",
    year: "2024",
    image: "/paintings/perforated-series-gallery-2.jpg",
    category: "perforated-newspaper",
  },
  {
    id: "perforated-series-gallery-3",
    title: "Black Mountain Series III",
    medium: "Acrylic on perforated Newspaper",
    size: "Installation view",
    year: "2024",
    image: "/paintings/perforated-series-gallery-3.jpg",
    category: "perforated-newspaper",
  },
  {
    id: "girl-with-plant-2",
    title: "Supa Hero's brother",
    medium: "Acrylic on canvas",
    size: "180 × 135 cm",
    year: "2024",
    image: "/paintings/girl-with-plant-2.jpg",
    category: "portrait",
  },
  {
    id: "studio-panorama",
    title: "Pa mpasa",
    medium: "Acrylic on canvas",
    size: "176 × 136 cm",
    year: "2024",
    image: "/paintings/studio-panorama.jpg",
    category: "landscape",
  },
];

export const featuredPaintings = paintings.filter((p) => p.featured);

export const categories = [
  { id: "all", label: "All Works" },
  { id: "portrait", label: "Portraits" },
  { id: "perforated-newspaper", label: "Perforated Newspaper" },
  { id: "monochrome", label: "Monochrome Series" },
  { id: "landscape", label: "Landscapes & Figures" },
] as const;
